# Generated by Django 4.2.5 on 2024-02-27 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintResponse',
            fields=[
                ('complaint_response_id', models.AutoField(primary_key=True, serialize=False)),
                ('response_description', models.TextField()),
                ('workshop_complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.workshopcomplaint')),
            ],
        ),
    ]
